services:
  - type: web
    name: saas-insight-api
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: .
    
  - type: web
    name: saas-insight-frontend
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npx serve -s build
    envVars:
      - key: NODE_ENV
        value: production 