services:
  - type: web
    name: saas-insight-engine-backend
    env: python
    plan: starter
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app
    healthCheckPath: /api/health
    autoDeploy: true
    disk:
      name: data-storage
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: REDDIT_USER_AGENT
        sync: false
      - key: DATAFORSEO_USERNAME
        sync: false
      - key: DATAFORSEO_PASSWORD
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://saas-insight-engine-frontend.onrender.com

  - type: web
    name: saas-insight-engine-frontend
    env: static
    plan: starter
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    autoDeploy: true
    envVars:
      - key: REACT_APP_STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: REACT_APP_API_URL
        value: https://saas-insight-engine-backend.onrender.com
      - key: NODE_ENV
        value: production 