services:
  - type: web
    name: saas-insight-engine-backend
    env: python
    plan: starter
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app
    healthCheckPath: /api/health
    autoDeploy: true
    disk:
      name: data-storage
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: REDDIT_USER_AGENT
        sync: false
      - key: DATAFORSEO_USERNAME
        sync: false
      - key: DATAFORSEO_PASSWORD
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: MAIL_SERVER
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USE_TLS
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://saas-insight-engine-frontend.onrender.com
      - key: ADDITIONAL_CORS_ORIGINS
        value: https://saas-engine.com

  - type: web
    name: saas-insight-engine-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=86400
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /static/js/*.js
        name: Content-Type
        value: application/javascript
      - path: /static/css/*.css
        name: Content-Type
        value: text/css
      - path: /static/media/*
        name: Content-Type
        value: image/svg+xml
    envVars:
      - key: REACT_APP_STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: REACT_APP_API_URL
        value: https://saas-insight-engine-backend.onrender.com
      - key: NODE_ENV
        value: production